# Generated by Django 4.1.2 on 2022-10-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=800)),
                ('fecha_atencion', models.DateField(auto_now_add=True)),
                ('hora_atencion', models.TimeField(auto_now_add=True)),
                ('consulta_pago', models.CharField(choices=[('e', 'Efectivo'), ('s', 'Asegurado')], default='e', max_length=35)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_proxima_consulta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_diag', models.CharField(max_length=400)),
                ('descripcion_diag', models.CharField(max_length=1000)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmed.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=35)),
                ('Aapellido', models.CharField(max_length=35)),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('municipio', models.CharField(max_length=35)),
                ('edad', models.CharField(max_length=12)),
                ('estado_civil', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(max_length=1000)),
                ('dieta', models.CharField(max_length=1000)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmed.consulta')),
                ('id_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmed.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_medicamento', models.CharField(max_length=100)),
                ('nombre_medicamento', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField(default=1)),
                ('tipo_medicamento', models.CharField(choices=[('f', 'Frasco'), ('p', 'Pastillas'), ('j', 'Jeringas'), ('s', 'Suero'), ('a', 'Ampollas')], default='f', max_length=35)),
                ('detalle', models.CharField(max_length=1000)),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmed.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('s', 'Sangre'), ('o', 'Orina'), ('h', 'Heces'), ('r', 'Rayos X'), ('e', 'Ecografia')], default='s', max_length=35)),
                ('detalle_examen', models.CharField(max_length=1000)),
                ('resultado_examen', models.CharField(max_length=1000)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmed.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmed.paciente'),
        ),
    ]
