# Generated by Django 4.1.2 on 2022-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado'), ('o', 'Otro')], default='s', max_length=35),
        ),
    ]
