# Generated by Django 4.1.2 on 2022-10-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0002_alter_paciente_estado_civil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Aapellido',
            new_name='apellido',
        ),
    ]
