# Generated by Django 4.1.2 on 2022-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0005_alter_paciente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=1),
        ),
    ]
