# Generated by Django 4.1.2 on 2022-10-05 17:18

import appmed.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0006_alter_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.CharField(max_length=800, validators=[appmed.validators.validar_motivo]),
        ),
    ]
