# Generated by Django 4.1.2 on 2022-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0007_alter_consulta_motivo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion_diag',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='detalle_examen',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='resultado_examen',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='detalle',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombre_medicamento',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='dieta',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='tratamiento',
            field=models.TextField(max_length=1000),
        ),
    ]
