# Generated by Django 4.1.2 on 2022-10-05 19:08

import appmed.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0008_alter_diagnostico_descripcion_diag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[appmed.validators.validar_talla]),
        ),
    ]
