# Generated by Django 4.1.2 on 2022-10-05 19:27

import appmed.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmed', '0009_alter_consulta_estatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[appmed.validators.validar_peso]),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion_diag',
            field=models.TextField(max_length=1000, validators=[appmed.validators.validar_descripcion]),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre_diag',
            field=models.CharField(max_length=400, validators=[appmed.validators.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='detalle_examen',
            field=models.TextField(max_length=1000, validators=[appmed.validators.validar_detalle_examen]),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='resultado_examen',
            field=models.TextField(max_length=1000, validators=[appmed.validators.validar_resultado_axamen]),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='codigo_medicamento',
            field=models.CharField(max_length=100, validators=[appmed.validators.validar_codigo_medicamento, appmed.validators.validar_codigo_sigla]),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='detalle',
            field=models.TextField(max_length=1000, validators=[appmed.validators.validar_detalle_medicamento]),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombre_medicamento',
            field=models.CharField(max_length=500, validators=[appmed.validators.validar_nombre_medicamento]),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='dieta',
            field=models.TextField(max_length=1000, validators=[appmed.validators.validar_dieta_tratamiento]),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='tratamiento',
            field=models.TextField(max_length=1000, validators=[appmed.validators.validar_tratamiento]),
        ),
    ]
